services:
  - type: web
    name: spillorama-system
    runtime: node
    region: frankfurt
    plan: starter
    buildCommand: npm install --include=dev && npm --prefix apps/backend install --include=dev && npm run build
    startCommand: npm --prefix apps/backend run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: SESSION_SECRET
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: APP_PG_CONNECTION_STRING
        sync: false
      - key: APP_PG_SCHEMA
        value: public
      - key: REDIS_HOST
        sync: false
      - key: REDIS_PORT
        sync: false
      - key: REDIS_PASSWORD
        sync: false
      - key: REDIS_TLS
        value: "true"
      - key: MSSQL_DB_SERVER
        sync: false
      - key: MSSQL_DB_DATABASE
        sync: false
      - key: MSSQL_DB_PORT
        sync: false
      - key: MSSQL_DB_USERNAME
        sync: false
      - key: MSSQL_DB_PASSWORD
        sync: false
      - key: DEFAULT_ADMIN_USER_LOGIN_EMAIL
        sync: false
      - key: DEFAULT_ADMIN_USER_LOGIN_PASSWORD
        sync: false
      - key: VERIFONE_ENTITY_ID
        sync: false
      - key: VERIFONE_CONTRACT_ID
        sync: false
      - key: VERIFONE_USER_ID
        sync: false
      - key: VERIFONE_API_ID
        sync: false
      - key: METRONIA_API_URL
        sync: false
      - key: METRONIA_API_TOKEN_TEST
        sync: false
      - key: IDKOLLEN_URL
        sync: false
      - key: IDKOLLEN_API_KEY
        sync: false
      - key: IDKOLLEN_SECRET
        sync: false
      - key: SVEVE_USERNAME
        sync: false
      - key: SVEVE_PASSWORD
        sync: false
      - key: SVEVE_SENDER
        sync: false
      - key: SWEDBANKPAY_PAYEE_ID
        sync: false
      - key: SWEDBANKPAY_TOKEN
        sync: false
      - key: SWEDBANKPAY_PAYEE_NAME
        sync: false
      - key: SWEDBANKPAY_PAYMENT_API_URL
        sync: false
      - key: SWEDBANKPAY_PAYMENT_CURRENCY_CODE
        value: NOK
      - key: SWEDBANKPAY_HOST_URLS
        sync: false
      - key: SWEDBANKPAY_PAYMENT_URL
        sync: false
      - key: SWEDBANKPAY_COMPLETE_URL
        sync: false
      - key: SWEDBANKPAY_CANCEL_URL
        sync: false
      - key: SWEDBANKPAY_CALLBACK_URL
        sync: false
      - key: SWEDBANKPAY_TERMS_OF_SERVICE_URL
        sync: false
      - key: FIREBASE_ADMIN_DB_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      # Candy integration
      - key: EXT_GAME_WALLET_API_KEY
        sync: false
      - key: CANDY_BACKEND_URL
        value: https://candy-backend-ldvg.onrender.com
      - key: CANDY_INTEGRATION_API_KEY
        sync: false
