/**
 * BIN-615 / PR-C2: Game 2 (Rocket/Tallspill) engine — extends BingoEngine
 * to add auto-claim-on-draw behaviour for the 3×3 / 1..21 variant.
 *
 * G1 rooms are unaffected — the G2 hook path is guarded by
 * `variantConfig.patternEvalMode === "auto-claim-on-draw"` AND the presence
 * of a 3×3 ticket grid. Every other room falls through to the BingoEngine
 * default `onDrawCompleted` (no-op), preserving G1 manual-claim semantics.
 *
 * Legacy references:
 *   - Game/Game2/Controllers/GameProcess.js:192-252 — draw loop + shouldStop
 *   - Game/Game2/Controllers/GameProcess.js:254-367 — checkForWinners
 *     (matched.length > 8 = full 3×3, triggers only after draw 9)
 *   - Game/Game2/Controllers/GameProcess.js:343-354 — TicketCompleted per-winner emit
 *   - gamehelper/game2.js:1466-1625 — normalize + checkJackPot (multi-winner split)
 *   - gamehelper/game2.js:1628-1712 — checkLuckyNumber (lastBall === luckyNumber bonus)
 *   - Game/Game2/Controllers/GameController.js:873-891 — game2JackpotUpdate (per-draw broadcast)
 *
 * Event emission is deferred to the socket layer via
 * {@link getG2LastDrawEffects}. Keeps the engine socket-agnostic.
 */

import { randomUUID } from "node:crypto";
import { BingoEngine } from "./BingoEngine.js";
import { IdempotencyKeys } from "./idempotency.js";
import { roundCurrency } from "../util/currency.js";
import { logger as rootLogger } from "../util/logger.js";
import { hasFull3x3 } from "./ticket.js";
import {
  computeJackpotList,
  resolveJackpotPrize,
  type JackpotListEntry,
} from "./Game2JackpotTable.js";
import type { GameState, Player, RoomState, ClaimRecord } from "./types.js";
import type { GameVariantConfig } from "./variantConfig.js";
import type { LedgerChannel, LedgerGameType } from "./ComplianceLedger.js";
import { ledgerGameTypeForSlug } from "./ledgerGameTypeForSlug.js";

const logger = rootLogger.child({ module: "engine.game2" });

/** Minimum draws required before winner check runs (legacy: >9 balls → check). */
export const GAME2_MIN_DRAWS_FOR_CHECK = 9;

/**
 * Per-draw G2 side-effects published to the socket layer.
 *
 * The socket handler (gameEvents.ts `draw:next`) reads this AFTER drawNextNumber
 * returns and emits the corresponding wire events:
 *   - g2:jackpot:list-update (always, when jackpotList is set)
 *   - g2:ticket:completed    (private, per winner)
 *   - g2:rocket:launch       (broadcast, once per round when game ends with winners)
 */
export interface G2DrawEffects {
  roomCode: string;
  gameId: string;
  drawIndex: number;
  lastBall: number;
  /** Updated per-draw jackpot display list — emitted on every G2 draw. */
  jackpotList: JackpotListEntry[];
  /** Non-empty when 9/9-completion was detected this draw. */
  winners: G2WinnerRecord[];
  /** True when the round ended as a result of winners being found. */
  gameEnded: boolean;
  /** When gameEnded, the terminal reason string set on game.endedReason. */
  endedReason?: string;
}

export interface G2WinnerRecord {
  playerId: string;
  /** Winner's ticket index within their ticket array (per room.tickets map). */
  ticketIndex: number;
  /** Optional stable ticket id if the Ticket carried one. */
  ticketId?: string;
  /** ClaimRecord.id — autoGenerated=true for all G2 auto-claims. */
  claimId: string;
  /** Jackpot prize in kr after split + cap. 0 when no jackpot entry matched. */
  jackpotPrize: number;
  /** Lucky-number bonus in kr (legacy game2.js:1628-1712). 0 when not triggered. */
  luckyBonus: number;
  /** Total credited to player's wallet this draw (jackpotPrize + luckyBonus after caps). */
  totalPayout: number;
}

export class Game2Engine extends BingoEngine {
  /**
   * BIN-615 / PR-C2: Side-effects stash per room. Populated by onDrawCompleted,
   * drained by the socket layer after drawNextNumber returns. The socket layer
   * calls {@link getG2LastDrawEffects} which atomically reads-and-clears.
   */
  private readonly lastDrawEffectsByRoom = new Map<string, G2DrawEffects>();

  /**
   * BIN-615 / PR-C2: Public reader for the socket layer. Returns undefined when
   * the last draw was not a G2 draw or effects have already been consumed.
   *
   * Atomic read-and-clear so the same effects aren't emitted twice on replay.
   */
  getG2LastDrawEffects(roomCode: string): G2DrawEffects | undefined {
    const effects = this.lastDrawEffectsByRoom.get(roomCode);
    if (effects) this.lastDrawEffectsByRoom.delete(roomCode);
    return effects;
  }

  /**
   * BIN-615 / PR-C1 hook (C2 override):
   *   - Non-G2 rooms → fall through to base no-op.
   *   - G2 rooms → compute jackpotList; if drawIndex ≥ 9, scan tickets for 9/9,
   *     run auto-claim + multi-winner payout + lucky-bonus, end game on winners.
   *
   * All side-effects stashed into lastDrawEffectsByRoom for the socket layer.
   */
  protected async onDrawCompleted(ctx: {
    room: RoomState;
    game: GameState;
    lastBall: number;
    drawIndex: number;
    variantConfig: GameVariantConfig | undefined;
  }): Promise<void> {
    const { room, game, lastBall, drawIndex, variantConfig } = ctx;
    if (!this.isGame2Round(variantConfig)) return;

    const purchasedTickets = countTickets(game);
    const ticketPrice = game.entryFee;
    const jackpotList = computeJackpotList(
      variantConfig!.jackpotNumberTable ?? {},
      purchasedTickets,
      ticketPrice,
    );

    if (drawIndex < GAME2_MIN_DRAWS_FOR_CHECK) {
      // Pre-check draws: publish jackpot list only.
      this.lastDrawEffectsByRoom.set(room.code, {
        roomCode: room.code,
        gameId: game.id,
        drawIndex,
        lastBall,
        jackpotList,
        winners: [],
        gameEnded: false,
      });
      return;
    }

    // Scan all tickets for 9/9 full-plate completion.
    const candidates = this.findG2Winners(room, game);
    if (candidates.length === 0) {
      this.lastDrawEffectsByRoom.set(room.code, {
        roomCode: room.code,
        gameId: game.id,
        drawIndex,
        lastBall,
        jackpotList,
        winners: [],
        gameEnded: false,
      });
      return;
    }

    // Resolve jackpot prize per current draw count (9..21 bucket semantics).
    const jackpotResolution = resolveJackpotPrize(
      variantConfig!.jackpotNumberTable ?? {},
      drawIndex,
      candidates.length,
      purchasedTickets,
      ticketPrice,
    );

    const winnerRecords: G2WinnerRecord[] = [];
    // K2-A CRIT-1 (utvidelse 2026-04-30): Spill 2 (slug `rocket`) er
    // hovedspill — bruk per-spill resolver for ledger-gameType. Resolver
    // er tolerant for null/manglende slug; faller til DATABINGO for å
    // bevare bakoverkompatibilitet for ukjente slugs.
    const gameType: LedgerGameType = ledgerGameTypeForSlug(room.gameSlug);
    const channel: LedgerChannel = "INTERNET";
    const houseAccountId = this.ledger.makeHouseAccountId(room.hallId, gameType, channel);

    for (const c of candidates) {
      const claimId = randomUUID();
      const claim: ClaimRecord = {
        id: claimId,
        playerId: c.player.id,
        type: "BINGO",
        valid: true,
        autoGenerated: true,
        createdAt: new Date().toISOString(),
        payoutAmount: 0,
      };

      // Jackpot payout (per-winner split from resolveJackpotPrize).
      let jackpotPaid = 0;
      if (jackpotResolution && jackpotResolution.pricePerWinner > 0) {
        jackpotPaid = await this.payG2JackpotShare({
          room,
          game,
          player: c.player,
          claim,
          requestedPayout: jackpotResolution.pricePerWinner,
          drawIndex,
          houseAccountId,
          gameType,
          channel,
        });
      }

      // Lucky-number bonus (legacy game2.js:1628-1712): paid only when
      // lastBall === this player's luckyNumber AND they won.
      let luckyPaid = 0;
      const luckyNumber = this.luckyNumbersByPlayer.get(room.code)?.get(c.player.id);
      const luckyPrize = variantConfig!.luckyNumberPrize ?? 0;
      if (luckyNumber !== undefined && luckyNumber === lastBall && luckyPrize > 0) {
        luckyPaid = await this.payG2LuckyBonus({
          room,
          game,
          player: c.player,
          claim,
          requestedPayout: luckyPrize,
          houseAccountId,
          gameType,
          channel,
        });
      }

      const totalPayout = roundCurrency(jackpotPaid + luckyPaid);
      claim.payoutAmount = totalPayout;
      game.claims.push(claim);

      if (this.bingoAdapter.onClaimLogged) {
        try {
          await this.bingoAdapter.onClaimLogged({
            roomCode: room.code,
            gameId: game.id,
            playerId: c.player.id,
            type: claim.type,
            valid: claim.valid,
            reason: claim.reason,
          });
        } catch (err) {
          logger.error({ err, gameId: game.id, roomCode: room.code }, "onClaimLogged failed for G2 auto-claim");
        }
      }

      winnerRecords.push({
        playerId: c.player.id,
        ticketIndex: c.ticketIndex,
        ticketId: c.ticketId,
        claimId,
        jackpotPrize: jackpotPaid,
        luckyBonus: luckyPaid,
        totalPayout,
      });
    }

    // End the round — legacy: once winners are found, no more draws.
    const endedAtMs = Date.now();
    game.bingoWinnerId = winnerRecords[0]?.playerId;
    game.status = "ENDED";
    game.endedAt = new Date(endedAtMs).toISOString();
    game.endedReason = "G2_WINNER";
    await this.finishPlaySessionsForGame(room, game, endedAtMs);
    await this.writeGameEndCheckpoint(room, game);
    await this.rooms.persist(room.code);

    this.lastDrawEffectsByRoom.set(room.code, {
      roomCode: room.code,
      gameId: game.id,
      drawIndex,
      lastBall,
      jackpotList,
      winners: winnerRecords,
      gameEnded: true,
      endedReason: "G2_WINNER",
    });
  }

  /**
   * BIN-615 / PR-C2: Detect all tickets that are 9/9 matched (full 3×3).
   * Returns one record per winning (player, ticket) pair — legacy can award
   * the same player multiple times if they hold >1 completed ticket.
   *
   * Legacy ref: GameProcess.js:280-312 (ticket chunking + matched > 8 check).
   */
  private findG2Winners(room: RoomState, game: GameState): Array<{
    player: Player;
    ticketIndex: number;
    ticketId?: string;
  }> {
    const drawnSet = new Set(game.drawnNumbers);
    const winners: Array<{ player: Player; ticketIndex: number; ticketId?: string }> = [];
    for (const player of room.players.values()) {
      const tickets = game.tickets.get(player.id);
      if (!tickets) continue;
      for (let i = 0; i < tickets.length; i += 1) {
        const t = tickets[i];
        if (hasFull3x3(t, drawnSet)) {
          winners.push({ player, ticketIndex: i, ticketId: t.id });
        }
      }
    }
    return winners;
  }

  /**
   * BIN-615 / PR-C2: Apply single-prize cap, transfer from house → player,
   * update balances + compliance ledger + payout audit. Returns the actual
   * credited amount (may be less than requested if capped or budget-limited).
   *
   * Mirrors BingoEngine's existing LINE/BINGO payout accounting (lines 1081-1132)
   * but scoped to per-winner G2 jackpot shares.
   */
  private async payG2JackpotShare(args: {
    room: RoomState;
    game: GameState;
    player: Player;
    claim: ClaimRecord;
    requestedPayout: number;
    drawIndex: number;
    houseAccountId: string;
    gameType: LedgerGameType;
    channel: LedgerChannel;
  }): Promise<number> {
    const { room, game, player, claim, requestedPayout, drawIndex, houseAccountId, gameType, channel } = args;
    const rtpBefore = roundCurrency(Math.max(0, game.remainingPayoutBudget));
    const capped = this.prizePolicy.applySinglePrizeCap({
      hallId: room.hallId,
      gameType: "DATABINGO",
      amount: requestedPayout,
    });
    const afterPoolCap = Math.min(capped.cappedAmount, game.remainingPrizePool);
    const payout = Math.max(0, Math.min(afterPoolCap, game.remainingPayoutBudget));
    if (payout <= 0) {
      claim.payoutWasCapped = requestedPayout > 0;
      claim.rtpCapped = afterPoolCap > 0 && game.remainingPayoutBudget <= 0;
      claim.rtpBudgetBefore = rtpBefore;
      claim.rtpBudgetAfter = rtpBefore;
      // Legacy behaviour: even a zero payout is logged via PayoutAuditTrail
      // so compliance can audit budget-exhaustion events.
      await this.payoutAudit.appendPayoutAuditEvent({
        kind: "CLAIM_PRIZE",
        claimId: claim.id,
        gameId: game.id,
        roomCode: room.code,
        hallId: room.hallId,
        policyVersion: capped.policy.id,
        amount: 0,
        walletId: player.walletId,
        playerId: player.id,
        sourceAccountId: houseAccountId,
        txIds: [],
      });
      return 0;
    }
    // PR-W3 wallet-split: payout er gevinst → krediter winnings-siden.
    const transfer = await this.walletAdapter.transfer(
      houseAccountId,
      player.walletId,
      payout,
      `G2 jackpot prize ${room.code}`,
      {
        idempotencyKey: IdempotencyKeys.game2Jackpot({
          gameId: game.id,
          claimId: claim.id,
        }),
        targetSide: "winnings",
      }
    );
    player.balance = roundCurrency(player.balance + payout);
    game.remainingPrizePool = roundCurrency(Math.max(0, game.remainingPrizePool - payout));
    game.remainingPayoutBudget = roundCurrency(Math.max(0, game.remainingPayoutBudget - payout));
    await this.compliance.recordLossEntry(player.walletId, room.hallId, {
      type: "PAYOUT",
      amount: payout,
      createdAtMs: Date.now()
    });
    await this.ledger.recordComplianceLedgerEvent({
      hallId: room.hallId,
      gameType,
      channel,
      eventType: "PRIZE",
      amount: payout,
      roomCode: room.code,
      gameId: game.id,
      claimId: claim.id,
      playerId: player.id,
      walletId: player.walletId,
      sourceAccountId: transfer.fromTx.accountId,
      targetAccountId: transfer.toTx.accountId,
      policyVersion: capped.policy.id
    });
    await this.payoutAudit.appendPayoutAuditEvent({
      kind: "CLAIM_PRIZE",
      claimId: claim.id,
      gameId: game.id,
      roomCode: room.code,
      hallId: room.hallId,
      policyVersion: capped.policy.id,
      amount: payout,
      walletId: player.walletId,
      playerId: player.id,
      sourceAccountId: houseAccountId,
      txIds: [transfer.fromTx.id, transfer.toTx.id]
    });
    claim.payoutTransactionIds = [...(claim.payoutTransactionIds ?? []), transfer.fromTx.id, transfer.toTx.id];
    claim.payoutPolicyVersion = capped.policy.id;
    claim.payoutWasCapped = payout < requestedPayout;
    claim.rtpBudgetBefore = rtpBefore;
    claim.rtpBudgetAfter = roundCurrency(Math.max(0, game.remainingPayoutBudget));
    claim.rtpCapped = payout < afterPoolCap;
    if (this.bingoAdapter.onCheckpoint) {
      await this.writePayoutCheckpointWithRetry(
        room, game, claim.id, payout,
        [transfer.fromTx.id, transfer.toTx.id],
        "BINGO"
      );
    }
    logger.info({
      event: "G2_JACKPOT_PAYOUT",
      roomCode: room.code,
      gameId: game.id,
      playerId: player.id,
      claimId: claim.id,
      drawIndex,
      requested: requestedPayout,
      paid: payout,
      capped: payout < requestedPayout
    }, "Game 2 jackpot share paid");
    return payout;
  }

  /**
   * BIN-615 / PR-C2: Lucky-number bonus payout — paid on top of jackpot when
   * lastBall === player.luckyNumber. Legacy ref: game2.js:1628-1712.
   *
   * Budget is shared with the jackpot payout — we reuse the game's
   * remainingPayoutBudget so total credited cannot exceed maxPayoutBudget.
   */
  private async payG2LuckyBonus(args: {
    room: RoomState;
    game: GameState;
    player: Player;
    claim: ClaimRecord;
    requestedPayout: number;
    houseAccountId: string;
    gameType: LedgerGameType;
    channel: LedgerChannel;
  }): Promise<number> {
    const { room, game, player, claim, requestedPayout, houseAccountId, gameType, channel } = args;
    const capped = this.prizePolicy.applySinglePrizeCap({
      hallId: room.hallId,
      gameType: "DATABINGO",
      amount: requestedPayout,
    });
    const afterPoolCap = Math.min(capped.cappedAmount, game.remainingPrizePool);
    const payout = Math.max(0, Math.min(afterPoolCap, game.remainingPayoutBudget));
    if (payout <= 0) return 0;
    // PR-W3 wallet-split: payout er gevinst → krediter winnings-siden.
    const transfer = await this.walletAdapter.transfer(
      houseAccountId,
      player.walletId,
      payout,
      `G2 lucky bonus ${room.code}`,
      {
        idempotencyKey: IdempotencyKeys.game2Lucky({
          gameId: game.id,
          claimId: claim.id,
        }),
        targetSide: "winnings",
      }
    );
    player.balance = roundCurrency(player.balance + payout);
    game.remainingPrizePool = roundCurrency(Math.max(0, game.remainingPrizePool - payout));
    game.remainingPayoutBudget = roundCurrency(Math.max(0, game.remainingPayoutBudget - payout));
    await this.compliance.recordLossEntry(player.walletId, room.hallId, {
      type: "PAYOUT",
      amount: payout,
      createdAtMs: Date.now()
    });
    await this.ledger.recordComplianceLedgerEvent({
      hallId: room.hallId,
      gameType,
      channel,
      eventType: "PRIZE",
      amount: payout,
      roomCode: room.code,
      gameId: game.id,
      claimId: claim.id,
      playerId: player.id,
      walletId: player.walletId,
      sourceAccountId: transfer.fromTx.accountId,
      targetAccountId: transfer.toTx.accountId,
      policyVersion: capped.policy.id
    });
    await this.payoutAudit.appendPayoutAuditEvent({
      kind: "CLAIM_PRIZE",
      claimId: claim.id,
      gameId: game.id,
      roomCode: room.code,
      hallId: room.hallId,
      policyVersion: capped.policy.id,
      amount: payout,
      walletId: player.walletId,
      playerId: player.id,
      sourceAccountId: houseAccountId,
      txIds: [transfer.fromTx.id, transfer.toTx.id]
    });
    claim.bonusTriggered = true;
    claim.bonusAmount = payout;
    claim.payoutTransactionIds = [...(claim.payoutTransactionIds ?? []), transfer.fromTx.id, transfer.toTx.id];
    logger.info({
      event: "G2_LUCKY_BONUS_PAYOUT",
      roomCode: room.code,
      gameId: game.id,
      playerId: player.id,
      claimId: claim.id,
      requested: requestedPayout,
      paid: payout
    }, "Game 2 lucky-number bonus paid");
    return payout;
  }

  /**
   * BIN-615 / PR-C2: guard predicate — true when the current round is a G2
   * auto-claim round. Used by onDrawCompleted to short-circuit for non-G2 rooms.
   *
   * Criteria:
   *   - variantConfig.patternEvalMode === "auto-claim-on-draw"
   *   - jackpotNumberTable defined (distinguishes G2 from future G3 auto-claim)
   *
   * G3 in PR-C3 will add its own guard (pattern-driven) and avoid G2 path.
   */
  private isGame2Round(variantConfig: GameVariantConfig | undefined): boolean {
    if (!variantConfig) return false;
    if (variantConfig.patternEvalMode !== "auto-claim-on-draw") return false;
    if (!variantConfig.jackpotNumberTable) return false;
    return true;
  }
}

function countTickets(game: GameState): number {
  let total = 0;
  for (const tickets of game.tickets.values()) total += tickets.length;
  return total;
}
