import type {
  RoomUpdatePayload,
  DrawNewPayload,
  PatternWonPayload,
  ChatMessage,
  JackpotActivatedPayload,
  MiniGameActivatedPayload,
} from "@spillorama/shared-types/socket-events";
import type {
  RoomSnapshot,
  GameSnapshot,
  Player,
  Ticket,
  PatternDefinition,
  PatternResult,
  GameStatus,
} from "@spillorama/shared-types/game";
import type { SpilloramaSocket } from "../net/SpilloramaSocket.js";

// ── Derived game state (what game scenes consume) ───────────────────────────

export interface GameState {
  roomCode: string;
  hallId: string;
  gameStatus: GameStatus | "NONE";
  gameId: string | null;
  players: Player[];
  playerCount: number;

  // Draw state
  drawnNumbers: number[];
  lastDrawnNumber: number | null;
  drawCount: number;
  totalDrawCapacity: number;

  // Tickets & marks
  myTickets: Ticket[];
  myMarks: number[][];
  myPlayerId: string | null;

  // Patterns
  patterns: PatternDefinition[];
  patternResults: PatternResult[];

  // Prize
  prizePool: number;
  entryFee: number;

  // Lucky number
  myLuckyNumber: number | null;
  luckyNumbers: Record<string, number>;

  // Scheduler
  millisUntilNextStart: number | null;
  autoDrawEnabled: boolean;
  /** A6: True when the host/admin can manually start the game right now. */
  canStartNow: boolean;

  // BIN-460: Game pause state
  isPaused: boolean;
  pauseMessage: string | null;

  // BIN-417: Active game variant info (from room:update.gameVariant)
  gameType: string;
  ticketTypes: Array<{ name: string; type: string; priceMultiplier: number; ticketCount: number }>;
  /** BIN-419: Elvis replace fee (kroner). 0 = no replace available. */
  replaceAmount: number;

  // Pre-round display tickets (always generated by backend, even for unarmed players)
  preRoundTickets: Ticket[];
  // True only when the player has explicitly armed (bet:arm) for the next round
  isArmed: boolean;

  /**
   * Server-authoritative stake in kroner.
   * Calculated by backend — the client never derives monetary amounts itself.
   * 0 = no active stake (player is spectating or hasn't bought).
   */
  myStake: number;

  // Server time for sync
  serverTimestamp: number;
}

// ── Event types ─────────────────────────────────────────────────────────────

export interface GameBridgeEvents {
  stateChanged: (state: GameState) => void;
  gameStarted: (state: GameState) => void;
  gameEnded: (state: GameState) => void;
  numberDrawn: (number: number, drawIndex: number, state: GameState) => void;
  patternWon: (result: PatternWonPayload, state: GameState) => void;
  chatMessage: (message: ChatMessage) => void;
  jackpotActivated: (data: JackpotActivatedPayload) => void;
  minigameActivated: (data: MiniGameActivatedPayload) => void;
}

type EventMap = {
  [K in keyof GameBridgeEvents]: Set<GameBridgeEvents[K]>;
};

// ── Bridge ──────────────────────────────────────────────────────────────────

/**
 * Translates raw socket events into game-specific derived state.
 * Replaces SpilloramaGameBridge.cs from Unity.
 *
 * Game scenes subscribe to high-level events (gameStarted, numberDrawn, etc.)
 * instead of parsing raw RoomUpdatePayload directly.
 */
export class GameBridge {
  private socket: SpilloramaSocket;
  private state: GameState;
  private myPlayerId: string | null = null;
  private previousGameStatus: GameStatus | "NONE" = "NONE";
  private unsubscribers: (() => void)[] = [];
  private events: EventMap = {
    stateChanged: new Set(),
    gameStarted: new Set(),
    gameEnded: new Set(),
    numberDrawn: new Set(),
    patternWon: new Set(),
    chatMessage: new Set(),
    jackpotActivated: new Set(),
    minigameActivated: new Set(),
  };

  constructor(socket: SpilloramaSocket) {
    this.socket = socket;
    this.state = this.createEmptyState();
  }

  // ── Lifecycle ─────────────────────────────────────────────────────────

  start(myPlayerId: string | null): void {
    this.myPlayerId = myPlayerId;
    this.state.myPlayerId = myPlayerId;

    this.unsubscribers.push(
      this.socket.on("roomUpdate", (payload) => this.handleRoomUpdate(payload)),
      this.socket.on("drawNew", (payload) => this.handleDrawNew(payload)),
      this.socket.on("patternWon", (payload) => this.handlePatternWon(payload)),
      this.socket.on("chatMessage", (msg) => this.emit("chatMessage", msg)),
      this.socket.on("jackpotActivated", (data) => this.emit("jackpotActivated", data)),
      this.socket.on("minigameActivated", (data) => this.emit("minigameActivated", data)),
    );
  }

  stop(): void {
    for (const unsub of this.unsubscribers) unsub();
    this.unsubscribers = [];
    this.state = this.createEmptyState();
  }

  getState(): GameState {
    return this.state;
  }

  // ── Event subscription ────────────────────────────────────────────────

  on<K extends keyof GameBridgeEvents>(
    event: K,
    listener: GameBridgeEvents[K],
  ): () => void {
    const set = this.events[event] as Set<GameBridgeEvents[K]>;
    set.add(listener);
    return () => set.delete(listener);
  }

  // ── Apply initial snapshot (from room:join response) ──────────────────

  applySnapshot(snapshot: RoomSnapshot): void {
    this.state.roomCode = snapshot.code;
    this.state.hallId = snapshot.hallId;
    this.state.players = snapshot.players;
    this.state.playerCount = snapshot.players.length;

    if (snapshot.currentGame) {
      this.applyGameSnapshot(snapshot.currentGame);
    } else {
      this.state.gameStatus = "NONE";
      this.state.gameId = null;
    }

    this.emit("stateChanged", this.state);
  }

  // ── Socket event handlers ─────────────────────────────────────────────

  private handleRoomUpdate(payload: RoomUpdatePayload): void {
    this.state.roomCode = payload.code;
    this.state.hallId = payload.hallId;
    this.state.players = payload.players;
    this.state.playerCount = payload.players.length;
    this.state.serverTimestamp = payload.serverTimestamp;
    this.state.luckyNumbers = payload.luckyNumbers;

    // Push balance to host page (game-bar sync)
    if (this.myPlayerId) {
      const me = payload.players.find((p: Player) => p.id === this.myPlayerId);
      if (me && typeof me.balance === "number" && typeof window !== "undefined") {
        window.dispatchEvent(new CustomEvent("spillorama:balanceChanged", { detail: { balance: me.balance } }));
      }
    }

    // Lucky number for this player
    if (this.myPlayerId && payload.luckyNumbers[this.myPlayerId] !== undefined) {
      this.state.myLuckyNumber = payload.luckyNumbers[this.myPlayerId];
    }

    // Pre-round tickets — backend always generates these for all non-participating players,
    // so presence alone doesn't mean the player has armed. Use armedPlayerIds for that.
    if (this.myPlayerId) {
      this.state.preRoundTickets = payload.preRoundTickets[this.myPlayerId] ?? [];
      this.state.isArmed = (payload.armedPlayerIds ?? []).includes(this.myPlayerId);
      // Server-authoritative stake — no client-side monetary calculation needed.
      this.state.myStake = payload.playerStakes?.[this.myPlayerId] ?? 0;
    }

    // Scheduler
    const scheduler = payload.scheduler as Record<string, unknown>;
    if (typeof scheduler?.millisUntilNextStart === "number") {
      this.state.millisUntilNextStart = scheduler.millisUntilNextStart;
    }
    if (typeof scheduler?.autoDrawEnabled === "boolean") {
      this.state.autoDrawEnabled = scheduler.autoDrawEnabled;
    }
    if (typeof scheduler?.canStartNow === "boolean") {
      this.state.canStartNow = scheduler.canStartNow;
    }

    // BIN-417: Game variant info
    if (payload.gameVariant) {
      this.state.gameType = payload.gameVariant.gameType ?? "standard";
      this.state.ticketTypes = (payload.gameVariant.ticketTypes ?? []) as GameState["ticketTypes"];
      this.state.replaceAmount = payload.gameVariant.replaceAmount ?? 0;
    }

    // Game state
    const prevStatus = this.previousGameStatus;
    if (payload.currentGame) {
      this.applyGameSnapshot(payload.currentGame);
    } else {
      this.state.gameStatus = "NONE";
      this.state.gameId = null;
    }

    // Detect game lifecycle transitions
    const newStatus = this.state.gameStatus;
    if (prevStatus !== "RUNNING" && newStatus === "RUNNING") {
      this.emit("gameStarted", this.state);
    }
    if (prevStatus === "RUNNING" && newStatus !== "RUNNING") {
      this.emit("gameEnded", this.state);
    }
    this.previousGameStatus = newStatus;

    this.emit("stateChanged", this.state);
  }

  private handleDrawNew(payload: DrawNewPayload): void {
    this.state.drawnNumbers.push(payload.number);
    this.state.lastDrawnNumber = payload.number;
    this.state.drawCount = this.state.drawnNumbers.length;
    this.emit("numberDrawn", payload.number, payload.drawIndex, this.state);
    this.emit("stateChanged", this.state);
  }

  private handlePatternWon(payload: PatternWonPayload): void {
    // Update local pattern results
    const existing = this.state.patternResults.find(
      (r) => r.patternId === payload.patternId,
    );
    if (existing) {
      existing.isWon = true;
      existing.winnerId = payload.winnerId;
      existing.wonAtDraw = payload.wonAtDraw;
      existing.payoutAmount = payload.payoutAmount;
    }
    this.emit("patternWon", payload, this.state);
    this.emit("stateChanged", this.state);
  }

  // ── Helpers ───────────────────────────────────────────────────────────

  private applyGameSnapshot(game: GameSnapshot): void {
    this.state.gameStatus = game.status;
    this.state.gameId = game.id;
    this.state.drawnNumbers = [...game.drawnNumbers];
    this.state.lastDrawnNumber =
      game.drawnNumbers.length > 0
        ? game.drawnNumbers[game.drawnNumbers.length - 1]
        : null;
    this.state.drawCount = game.drawnNumbers.length;
    this.state.totalDrawCapacity = game.drawBag.length + game.drawnNumbers.length;
    this.state.prizePool = game.prizePool;
    this.state.entryFee = game.entryFee;
    this.state.patterns = game.patterns || [];
    this.state.patternResults = game.patternResults || [];
    this.state.isPaused = game.isPaused ?? false;
    this.state.pauseMessage = game.pauseMessage ?? null;

    // My tickets and marks
    if (this.myPlayerId) {
      this.state.myTickets = game.tickets[this.myPlayerId] || [];
      this.state.myMarks = game.marks[this.myPlayerId] || [];
    }
  }

  private createEmptyState(): GameState {
    return {
      roomCode: "",
      hallId: "",
      gameStatus: "NONE",
      gameId: null,
      players: [],
      playerCount: 0,
      drawnNumbers: [],
      lastDrawnNumber: null,
      drawCount: 0,
      totalDrawCapacity: 0,
      myTickets: [],
      myMarks: [],
      myPlayerId: null,
      patterns: [],
      patternResults: [],
      prizePool: 0,
      entryFee: 0,
      myLuckyNumber: null,
      luckyNumbers: {},
      millisUntilNextStart: null,
      autoDrawEnabled: false,
      canStartNow: false,
      isPaused: false,
      pauseMessage: null,
      gameType: "standard",
      ticketTypes: [],
      replaceAmount: 0,
      preRoundTickets: [],
      isArmed: false,
      myStake: 0,
      serverTimestamp: 0,
    };
  }

  private emit<K extends keyof GameBridgeEvents>(
    event: K,
    ...args: Parameters<GameBridgeEvents[K]>
  ): void {
    const set = this.events[event];
    for (const fn of set) {
      (fn as (...a: unknown[]) => void)(...args);
    }
  }
}
