import type {
  RoomUpdatePayload,
  DrawNewPayload,
  PatternWonPayload,
  ChatMessage,
  JackpotActivatedPayload,
  MiniGameActivatedPayload,
} from "@spillorama/shared-types/socket-events";
import type {
  RoomSnapshot,
  GameSnapshot,
  Player,
  Ticket,
  PatternDefinition,
  PatternResult,
  GameStatus,
} from "@spillorama/shared-types/game";
import type { SpilloramaSocket } from "../net/SpilloramaSocket.js";

// ── Derived game state (what game scenes consume) ───────────────────────────

export interface GameState {
  roomCode: string;
  hallId: string;
  gameStatus: GameStatus | "NONE";
  gameId: string | null;
  players: Player[];
  playerCount: number;

  // Draw state
  drawnNumbers: number[];
  lastDrawnNumber: number | null;
  drawCount: number;
  totalDrawCapacity: number;

  // Tickets & marks
  myTickets: Ticket[];
  myMarks: number[][];
  myPlayerId: string | null;

  // Patterns
  patterns: PatternDefinition[];
  patternResults: PatternResult[];

  // Prize
  prizePool: number;
  entryFee: number;

  // Lucky number
  myLuckyNumber: number | null;
  luckyNumbers: Record<string, number>;

  // Scheduler
  millisUntilNextStart: number | null;
  autoDrawEnabled: boolean;
  /** A6: True when the host/admin can manually start the game right now. */
  canStartNow: boolean;
  /** BIN-451: Draw count after which buy-more is disabled (server-authoritative). */
  disableBuyAfterBalls: number;

  // BIN-460: Game pause state
  isPaused: boolean;
  pauseMessage: string | null;

  // BIN-417: Active game variant info (from room:update.gameVariant)
  gameType: string;
  ticketTypes: Array<{ name: string; type: string; priceMultiplier: number; ticketCount: number }>;
  /** BIN-419: Elvis replace fee (kroner). 0 = no replace available. */
  replaceAmount: number;
  /**
   * F3 (BIN-431): Jackpot header info (from room:update.gameVariant.jackpot).
   * Null when the variant has no jackpot configured; falsy isDisplay = hide.
   * Unity reference: Game1GamePlayPanel.SocketFlow.cs:518-520.
   */
  jackpot: { drawThreshold: number; prize: number; isDisplay: boolean } | null;

  // Pre-round display tickets (always generated by backend, even for unarmed players)
  preRoundTickets: Ticket[];
  // True only when the player has explicitly armed (bet:arm) for the next round
  isArmed: boolean;

  /**
   * Server-authoritative stake in kroner.
   * Calculated by backend — the client never derives monetary amounts itself.
   * 0 = no active stake (player is spectating or hasn't bought).
   */
  myStake: number;

  // Server time for sync
  serverTimestamp: number;
}

// ── Event types ─────────────────────────────────────────────────────────────

export interface GameBridgeEvents {
  stateChanged: (state: GameState) => void;
  gameStarted: (state: GameState) => void;
  gameEnded: (state: GameState) => void;
  numberDrawn: (number: number, drawIndex: number, state: GameState) => void;
  patternWon: (result: PatternWonPayload, state: GameState) => void;
  chatMessage: (message: ChatMessage) => void;
  jackpotActivated: (data: JackpotActivatedPayload) => void;
  minigameActivated: (data: MiniGameActivatedPayload) => void;
}

type EventMap = {
  [K in keyof GameBridgeEvents]: Set<GameBridgeEvents[K]>;
};

// ── Bridge ──────────────────────────────────────────────────────────────────

/**
 * Translates raw socket events into game-specific derived state.
 * Replaces SpilloramaGameBridge.cs from Unity.
 *
 * Game scenes subscribe to high-level events (gameStarted, numberDrawn, etc.)
 * instead of parsing raw RoomUpdatePayload directly.
 */
export class GameBridge {
  private socket: SpilloramaSocket;
  private state: GameState;
  private myPlayerId: string | null = null;
  private previousGameStatus: GameStatus | "NONE" = "NONE";
  private unsubscribers: (() => void)[] = [];

  /**
   * BIN-502: Last drawIndex we have applied. `-1` means no draws received yet
   * in the current game. Reset to `-1` on applyGameSnapshot (fresh baseline)
   * and on gameStatus transitions to new RUNNING.
   */
  private lastAppliedDrawIndex = -1;

  /**
   * BIN-502: Guard against concurrent resync requests. Once we detect a gap we
   * kick off one resync and wait for snapshot before we trust drawNew again.
   */
  private resyncInFlight = false;

  /**
   * BIN-502: Client-side metric counter for observability (BIN-539 will wire
   * this into Sentry/Prometheus). Read via `getGapMetrics()` for tests.
   */
  private drawGapCount = 0;
  private drawDuplicateCount = 0;

  private events: EventMap = {
    stateChanged: new Set(),
    gameStarted: new Set(),
    gameEnded: new Set(),
    numberDrawn: new Set(),
    patternWon: new Set(),
    chatMessage: new Set(),
    jackpotActivated: new Set(),
    minigameActivated: new Set(),
  };

  constructor(socket: SpilloramaSocket) {
    this.socket = socket;
    this.state = this.createEmptyState();
  }

  // ── Lifecycle ─────────────────────────────────────────────────────────

  start(myPlayerId: string | null): void {
    this.myPlayerId = myPlayerId;
    this.state.myPlayerId = myPlayerId;

    this.unsubscribers.push(
      this.socket.on("roomUpdate", (payload) => this.handleRoomUpdate(payload)),
      this.socket.on("drawNew", (payload) => this.handleDrawNew(payload)),
      this.socket.on("patternWon", (payload) => this.handlePatternWon(payload)),
      this.socket.on("chatMessage", (msg) => this.emit("chatMessage", msg)),
      this.socket.on("jackpotActivated", (data) => this.emit("jackpotActivated", data)),
      this.socket.on("minigameActivated", (data) => this.emit("minigameActivated", data)),
    );
  }

  stop(): void {
    for (const unsub of this.unsubscribers) unsub();
    this.unsubscribers = [];
    this.state = this.createEmptyState();
    // BIN-502: reset gap-detection bookkeeping so a re-`start()` behaves fresh.
    this.lastAppliedDrawIndex = -1;
    this.resyncInFlight = false;
    this.drawGapCount = 0;
    this.drawDuplicateCount = 0;
  }

  getState(): GameState {
    return this.state;
  }

  // ── Event subscription ────────────────────────────────────────────────

  on<K extends keyof GameBridgeEvents>(
    event: K,
    listener: GameBridgeEvents[K],
  ): () => void {
    const set = this.events[event] as Set<GameBridgeEvents[K]>;
    set.add(listener);
    return () => set.delete(listener);
  }

  // ── Apply initial snapshot (from room:join response) ──────────────────

  applySnapshot(snapshot: RoomSnapshot): void {
    this.state.roomCode = snapshot.code;
    this.state.hallId = snapshot.hallId;
    this.state.players = snapshot.players;
    this.state.playerCount = snapshot.players.length;

    if (snapshot.currentGame) {
      // BIN-686: Full snapshot-apply path — reset gap-detection baseline
      // so draw:new from this point forward can validate correctly.
      this.applyGameSnapshot(snapshot.currentGame, { resetDrawIndex: true });
    } else {
      this.state.gameStatus = "NONE";
      this.state.gameId = null;
      // Also reset index — a null currentGame means we're between rounds.
      this.lastAppliedDrawIndex = -1;
    }
    // BIN-686: seed previousGameStatus from the applied snapshot so the
    // first incoming room:update doesn't mistake this for a WAITING→RUNNING
    // transition (which would trigger an unwanted lastAppliedDrawIndex
    // reset and drop the next draw:new as a duplicate).
    this.previousGameStatus = this.state.gameStatus;

    // The server's room:create ack returns a full RoomUpdatePayload, not a bare
    // RoomSnapshot. Pull variant info from it so the buy popup gets ticket types
    // immediately — otherwise we'd have to wait for the next room:update push,
    // which can race with our listener registration.
    const payload = snapshot as RoomSnapshot & { gameVariant?: RoomUpdatePayload["gameVariant"]; serverTimestamp?: number };
    if (payload.gameVariant) {
      this.state.gameType = payload.gameVariant.gameType ?? "standard";
      this.state.ticketTypes = (payload.gameVariant.ticketTypes ?? []) as GameState["ticketTypes"];
      this.state.replaceAmount = payload.gameVariant.replaceAmount ?? 0;
      this.state.jackpot = payload.gameVariant.jackpot ?? null;
      const variantFee = payload.gameVariant.entryFee;
      if (typeof variantFee === "number" && variantFee > 0 && this.state.entryFee === 0) {
        this.state.entryFee = variantFee;
      }
    }
    if (typeof payload.serverTimestamp === "number") {
      this.state.serverTimestamp = payload.serverTimestamp;
    }

    this.emit("stateChanged", this.state);
  }

  // ── Socket event handlers ─────────────────────────────────────────────

  private handleRoomUpdate(payload: RoomUpdatePayload): void {
    this.state.roomCode = payload.code;
    this.state.hallId = payload.hallId;
    this.state.players = payload.players;
    this.state.playerCount = payload.players.length;
    this.state.serverTimestamp = payload.serverTimestamp;
    this.state.luckyNumbers = payload.luckyNumbers;

    // Push balance to host page (game-bar sync)
    if (this.myPlayerId) {
      const me = payload.players.find((p: Player) => p.id === this.myPlayerId);
      if (me && typeof me.balance === "number" && typeof window !== "undefined") {
        window.dispatchEvent(new CustomEvent("spillorama:balanceChanged", { detail: { balance: me.balance } }));
      }
    }

    // Lucky number for this player
    if (this.myPlayerId && payload.luckyNumbers[this.myPlayerId] !== undefined) {
      this.state.myLuckyNumber = payload.luckyNumbers[this.myPlayerId];
    }

    // Pre-round tickets — backend always generates these for all non-participating players,
    // so presence alone doesn't mean the player has armed. Use armedPlayerIds for that.
    if (this.myPlayerId) {
      this.state.preRoundTickets = payload.preRoundTickets[this.myPlayerId] ?? [];
      this.state.isArmed = (payload.armedPlayerIds ?? []).includes(this.myPlayerId);
      // Server-authoritative stake — no client-side monetary calculation needed.
      this.state.myStake = payload.playerStakes?.[this.myPlayerId] ?? 0;
    }

    // Scheduler
    const scheduler = payload.scheduler as Record<string, unknown>;
    if (typeof scheduler?.millisUntilNextStart === "number") {
      this.state.millisUntilNextStart = scheduler.millisUntilNextStart;
    }
    if (typeof scheduler?.autoDrawEnabled === "boolean") {
      this.state.autoDrawEnabled = scheduler.autoDrawEnabled;
    }
    if (typeof scheduler?.canStartNow === "boolean") {
      this.state.canStartNow = scheduler.canStartNow;
    }
    if (typeof scheduler?.disableBuyAfterBalls === "number") {
      this.state.disableBuyAfterBalls = scheduler.disableBuyAfterBalls;
    }

    // BIN-417: Game variant info
    if (payload.gameVariant) {
      this.state.gameType = payload.gameVariant.gameType ?? "standard";
      this.state.ticketTypes = (payload.gameVariant.ticketTypes ?? []) as GameState["ticketTypes"];
      this.state.replaceAmount = payload.gameVariant.replaceAmount ?? 0;
      // F3 (BIN-431): Jackpot header info. null when variant has no jackpot.
      this.state.jackpot = payload.gameVariant.jackpot ?? null;
      // Backend exposes the room's configured entry fee here so the buy popup
      // can render prices before a game is RUNNING. Don't overwrite an active
      // game's entryFee (already set via applyGameSnapshot below).
      const variantFee = payload.gameVariant.entryFee;
      if (typeof variantFee === "number" && variantFee > 0 && this.state.entryFee === 0) {
        this.state.entryFee = variantFee;
      }
    }

    // Game state
    const prevStatus = this.previousGameStatus;
    const prevGameId = this.state.gameId;
    if (payload.currentGame) {
      // BIN-686 Bug 3: Reset gap-detection baseline ONLY on a NEW game
      // (different gameId) or when transitioning into RUNNING from a non-
      // running state. Within an active round, room:update races with
      // draw:new so we MUST keep lastAppliedDrawIndex stable — otherwise
      // every room:update re-baselines and makes the next draw:new look
      // like a gap, triggering an infinite resync loop.
      const isNewGame = payload.currentGame.id !== prevGameId;
      const isRoundStart = prevStatus !== "RUNNING" && payload.currentGame.status === "RUNNING";
      this.applyGameSnapshot(payload.currentGame, { resetDrawIndex: isNewGame || isRoundStart });
    } else {
      this.state.gameStatus = "NONE";
      this.state.gameId = null;
      this.lastAppliedDrawIndex = -1;
    }

    // Detect game lifecycle transitions
    const newStatus = this.state.gameStatus;
    if (prevStatus !== "RUNNING" && newStatus === "RUNNING") {
      this.emit("gameStarted", this.state);
    }
    if (prevStatus === "RUNNING" && newStatus !== "RUNNING") {
      this.emit("gameEnded", this.state);
    }
    this.previousGameStatus = newStatus;

    this.emit("stateChanged", this.state);
  }

  /**
   * BIN-502: Apply draw:new with drawIndex gap-detection.
   *
   * Expected sequence: drawIndex = lastAppliedDrawIndex + 1.
   * - Duplicate (drawIndex <= lastAppliedDrawIndex): ignore (reconnect replay).
   * - Gap (drawIndex > lastAppliedDrawIndex + 1): we missed one or more draws.
   *   Trigger a room:state resync and drop this event — snapshot will catch us up.
   * - Ordered: apply normally.
   */
  private handleDrawNew(payload: DrawNewPayload): void {
    const expected = this.lastAppliedDrawIndex + 1;

    if (payload.drawIndex < expected) {
      // Duplicate — reconnect/replay scenario. Ignore.
      this.drawDuplicateCount += 1;
      console.debug(
        "[GameBridge] drawNew duplicate ignored",
        { got: payload.drawIndex, expected },
      );
      return;
    }

    if (payload.drawIndex > expected) {
      // Gap — we missed one or more draws. Trigger resync.
      this.drawGapCount += 1;
      console.warn(
        "[GameBridge] drawNew gap detected — requesting room:state resync",
        { got: payload.drawIndex, expected, gapSize: payload.drawIndex - expected },
      );
      this.requestResync();
      return;
    }

    // Ordered — apply.
    this.state.drawnNumbers.push(payload.number);
    this.state.lastDrawnNumber = payload.number;
    this.state.drawCount = this.state.drawnNumbers.length;
    this.lastAppliedDrawIndex = payload.drawIndex;
    this.emit("numberDrawn", payload.number, payload.drawIndex, this.state);
    this.emit("stateChanged", this.state);
  }

  /**
   * BIN-502: Request authoritative room state from backend to close a gap.
   * Guards against concurrent calls — once one resync is in flight we wait
   * for applySnapshot/applyGameSnapshot to reset `lastAppliedDrawIndex`.
   */
  private requestResync(): void {
    if (this.resyncInFlight) return;
    if (!this.state.roomCode) {
      console.warn("[GameBridge] cannot resync — no roomCode");
      return;
    }
    this.resyncInFlight = true;

    this.socket
      .getRoomState({ roomCode: this.state.roomCode, hallId: this.state.hallId || undefined })
      .then((ack) => {
        if (ack.ok && ack.data?.snapshot) {
          this.applySnapshot(ack.data.snapshot);
        } else {
          console.warn("[GameBridge] resync failed", ack);
        }
      })
      .catch((err) => {
        console.error("[GameBridge] resync threw", err);
      })
      .finally(() => {
        this.resyncInFlight = false;
      });
  }

  /** BIN-502: Observability hook — read gap/duplicate counters. */
  getGapMetrics(): { gaps: number; duplicates: number; lastAppliedDrawIndex: number } {
    return {
      gaps: this.drawGapCount,
      duplicates: this.drawDuplicateCount,
      lastAppliedDrawIndex: this.lastAppliedDrawIndex,
    };
  }

  private handlePatternWon(payload: PatternWonPayload): void {
    // Update local pattern results
    const existing = this.state.patternResults.find(
      (r) => r.patternId === payload.patternId,
    );
    if (existing) {
      existing.isWon = true;
      existing.winnerId = payload.winnerId;
      existing.wonAtDraw = payload.wonAtDraw;
      existing.payoutAmount = payload.payoutAmount;
    }
    this.emit("patternWon", payload, this.state);
    this.emit("stateChanged", this.state);
  }

  // ── Helpers ───────────────────────────────────────────────────────────

  private applyGameSnapshot(game: GameSnapshot, opts: { resetDrawIndex?: boolean } = {}): void {
    this.state.gameStatus = game.status;
    this.state.gameId = game.id;
    this.state.drawnNumbers = [...game.drawnNumbers];
    this.state.lastDrawnNumber =
      game.drawnNumbers.length > 0
        ? game.drawnNumbers[game.drawnNumbers.length - 1]
        : null;
    this.state.drawCount = game.drawnNumbers.length;
    // BIN-686 Bug 3: Only reset `lastAppliedDrawIndex` when called from a
    // FULL-snapshot path (applySnapshot / resyncRoom). `room:update` events
    // also carry a currentGame snapshot, but they RACE with draw:new events
    // — if we reset lastAppliedDrawIndex on every room:update, the next
    // draw:new looks like a gap (`drawIndex < expected`) and fires an
    // infinite resync loop. Keeping the existing index on room:update lets
    // draw:new's own bookkeeping stay consistent.
    if (opts.resetDrawIndex) {
      this.lastAppliedDrawIndex = game.drawnNumbers.length - 1;
    }
    this.state.totalDrawCapacity = game.drawBag.length + game.drawnNumbers.length;
    this.state.prizePool = game.prizePool;
    this.state.entryFee = game.entryFee;
    this.state.patterns = game.patterns || [];
    this.state.patternResults = game.patternResults || [];
    this.state.isPaused = game.isPaused ?? false;
    this.state.pauseMessage = game.pauseMessage ?? null;

    // My tickets and marks
    if (this.myPlayerId) {
      this.state.myTickets = game.tickets[this.myPlayerId] || [];
      this.state.myMarks = game.marks[this.myPlayerId] || [];
    }
  }

  private createEmptyState(): GameState {
    return {
      roomCode: "",
      hallId: "",
      gameStatus: "NONE",
      gameId: null,
      players: [],
      playerCount: 0,
      drawnNumbers: [],
      lastDrawnNumber: null,
      drawCount: 0,
      totalDrawCapacity: 0,
      myTickets: [],
      myMarks: [],
      myPlayerId: null,
      patterns: [],
      patternResults: [],
      prizePool: 0,
      entryFee: 0,
      myLuckyNumber: null,
      luckyNumbers: {},
      millisUntilNextStart: null,
      autoDrawEnabled: false,
      canStartNow: false,
      disableBuyAfterBalls: 0,
      isPaused: false,
      pauseMessage: null,
      gameType: "standard",
      ticketTypes: [],
      replaceAmount: 0,
      jackpot: null,
      preRoundTickets: [],
      isArmed: false,
      myStake: 0,
      serverTimestamp: 0,
    };
  }

  private emit<K extends keyof GameBridgeEvents>(
    event: K,
    ...args: Parameters<GameBridgeEvents[K]>
  ): void {
    const set = this.events[event];
    for (const fn of set) {
      (fn as (...a: unknown[]) => void)(...args);
    }
  }
}
